# Generated by Django 5.0.4 on 2026-05-09 04:51

import django.core.validators
from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_hash', models.CharField(db_index=True, help_text='MD5 hash of route parameters for caching', max_length=32, unique=True)),
                ('start_address', models.CharField(max_length=255)),
                ('end_address', models.CharField(max_length=255)),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
                ('total_distance', models.FloatField(help_text='Total distance in miles')),
                ('total_fuel_needed', models.FloatField(help_text='Total fuel needed in gallons')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost in USD', max_digits=10)),
                ('fuel_stops', models.JSONField(help_text='List of optimal fuel stops')),
                ('route_polyline', models.TextField(blank=True, help_text='Google Maps encoded polyline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Cache expiration time')),
                ('api_calls_saved', models.IntegerField(default=1, help_text='Number of API calls saved')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['route_hash', 'created_at'], name='fuel_routin_route_h_9a4bc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TruckStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(db_index=True, help_text='Truckstop Name', max_length=255)),
                ('address', models.TextField(help_text='Street Address')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.FloatField(db_index=True, help_text='Latitude coordinate')),
                ('longitude', models.FloatField(db_index=True, help_text='Longitude coordinate')),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=2, help_text='Price per gallon in USD', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_price_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Truck Stops',
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['state', 'city'], name='fuel_routin_state_4d7e31_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_routin_latitud_7ecba3_idx'), models.Index(fields=['retail_price', 'is_active'], name='fuel_routin_retail__a89fd2_idx')],
            },
        ),
    ]
