# Generated by Django 5.0.4 on 2026-05-10 19:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS ID (joins fuel_stations)')),
                ('price_per_gallon', models.DecimalField(decimal_places=3, help_text='Price per gallon in USD (1.000 to 9.999)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('9.99'))])),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINE', 'Gasoline')], default='DIESEL', help_text='Type of fuel', max_length=20)),
                ('observed_at', models.DateTimeField(help_text='When price was observed')),
                ('effective_from', models.DateTimeField(help_text='When price became effective')),
                ('effective_until', models.DateTimeField(default=django.utils.timezone.now, help_text='When price expires')),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='Only latest observation per OPIS ID = true per version')),
                ('is_available', models.BooleanField(default=True, help_text='Pump is operational')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('data_source', models.CharField(default='api', help_text='Data source (api, manual, etc.)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Fuel Prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID (external identifier)', unique=True)),
                ('name', models.CharField(db_index=True, help_text='Truck stop name', max_length=255)),
                ('address', models.TextField(help_text='Street address')),
                ('city', models.CharField(db_index=True, help_text='City name', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='2-letter state code (US only)', max_length=2)),
                ('country', models.CharField(default='US', help_text="Country code (always 'US')", max_length=2)),
                ('location', models.TextField(default='0,0', help_text='Geographic coordinates (lat,lon format)')),
                ('location_geography', models.TextField(default='0,0', help_text='Geographic coordinates for distance (lat,lon)')),
                ('latitude', models.FloatField(help_text='Latitude (denormalized from location)')),
                ('longitude', models.FloatField(help_text='Longitude (denormalized from location)')),
                ('rack_id', models.IntegerField(help_text='Rack/pump identifier')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Station actively accepting fuel orders')),
                ('quality_score', models.SmallIntegerField(default=100, help_text='Data quality score (0-100) from preprocessing', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_verified_at', models.DateTimeField(auto_now_add=True, help_text='Last verification timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('data_source_version', models.CharField(default='preprocessing_v1', help_text='Version of preprocessing that created this record', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Fuel Stations',
                'ordering': ['-is_active', 'state', 'city'],
            },
        ),
        migrations.CreateModel(
            name='GeocodeFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_address', models.TextField(help_text='Address that failed geocoding')),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State code', max_length=2)),
                ('failure_reason', models.CharField(help_text='Why geocoding failed', max_length=255)),
                ('google_error_code', models.CharField(blank=True, help_text='Google Geocoding API error code', max_length=50, null=True)),
                ('google_error_message', models.TextField(blank=True, help_text='Google error message', null=True)),
                ('retry_count', models.SmallIntegerField(default=0, help_text='Number of retry attempts', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='Last retry timestamp', null=True)),
                ('next_retry_at', models.DateTimeField(db_index=True, help_text='When to retry next (exponential backoff)')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, help_text='Geocoding succeeded')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When geocoding succeeded', null=True)),
                ('resolved_latitude', models.FloatField(blank=True, help_text='Resolved latitude', null=True)),
                ('resolved_longitude', models.FloatField(blank=True, help_text='Resolved longitude', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When failure was recorded')),
            ],
            options={
                'verbose_name_plural': 'Geocode Failures',
                'ordering': ['retry_count', 'next_retry_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Unique cache key (route_hash + version)', max_length=128, unique=True)),
                ('total_distance_miles', models.FloatField(help_text='Total route distance')),
                ('total_fuel_needed', models.FloatField(help_text='Gallons of fuel needed', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, help_text='Total fuel cost in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fuel_stop_count', models.SmallIntegerField(help_text='Number of fuel stops (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fuel_stops_json', models.JSONField(help_text='Detailed fuel stops array:\n        [\n          {\n            "opis_id": 9,\n            "name": "KWIK TRIP #796",\n            "city": "Tomah",\n            "state": "WI",\n            "latitude": 43.95,\n            "longitude": -90.52,\n            "price_per_gallon": 3.287,\n            "distance_from_start": 125.3,\n            "distance_to_next_stop": 98.5,\n            "gallons_needed": 12.5,\n            "cost": 41.09,\n            "detour_miles": 5.2\n          },\n          ...\n        ]')),
                ('computation_time_ms', models.IntegerField(help_text='Time to compute optimization (ms)')),
                ('api_calls_saved', models.SmallIntegerField(default=1, help_text='Number of API calls saved by cache')),
                ('is_valid', models.BooleanField(db_index=True, default=True, help_text='Optimization is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When optimization was computed')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When cache expires')),
            ],
            options={
                'verbose_name_plural': 'Optimization Caches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(db_index=True, help_text='Sequential version number (1, 2, 3, ...)', unique=True)),
                ('version_hash', models.CharField(help_text='MD5 hash of all prices (integrity check)', max_length=32, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Current active version (only one = true)')),
                ('is_published', models.BooleanField(default=False, help_text='Validated and ready for use')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When version was created')),
                ('published_at', models.DateTimeField(blank=True, help_text='When version was published', null=True)),
                ('expires_at', models.DateTimeField(help_text='When version expires (cleanup time)')),
                ('total_stations', models.IntegerField(default=5141, help_text='Number of stations with prices')),
                ('total_records', models.IntegerField(help_text='Total price records (stations × fuel types)')),
                ('source', models.CharField(default='api', help_text='Price source (api, manual, etc.)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Price Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='MD5(normalize(start) + normalize(end))', max_length=128, unique=True)),
                ('start_address', models.CharField(help_text='Starting address (normalized)', max_length=255)),
                ('end_address', models.CharField(help_text='Ending address (normalized)', max_length=255)),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
                ('route_polyline', models.TextField(default='', help_text='Route polyline (development)')),
                ('route_geography', models.TextField(default='', help_text='Route geography (development)')),
                ('total_distance_miles', models.FloatField(help_text='Total route distance in miles', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3000)])),
                ('google_polyline', models.TextField(help_text='Encoded polyline from Google Routes API')),
                ('google_duration_secs', models.IntegerField(help_text='Estimated duration in seconds')),
                ('google_api_cost', models.DecimalField(decimal_places=2, help_text='API cost estimate (in units)', max_digits=5)),
                ('is_valid', models.BooleanField(db_index=True, default=True, help_text='Route is still valid')),
                ('route_version', models.SmallIntegerField(default=1, help_text='Version of route (for updates)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When route was cached')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When cache expires')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, help_text='Last access timestamp (for LRU eviction)')),
                ('access_count', models.IntegerField(default=1, help_text='Number of times this route was used')),
                ('computation_time_ms', models.IntegerField(help_text='Time to compute route (ms)')),
            ],
            options={
                'verbose_name_plural': 'Route Caches',
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, help_text='UUID for request correlation/tracing', max_length=36, unique=True)),
                ('start_address', models.CharField(help_text='Starting address', max_length=255)),
                ('end_address', models.CharField(help_text='Ending address', max_length=255)),
                ('total_distance_miles', models.FloatField(help_text='Total distance miles')),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, help_text='Total fuel cost', max_digits=10)),
                ('fuel_stop_count', models.SmallIntegerField(help_text='Number of stops')),
                ('optimization_time_ms', models.IntegerField(help_text='Total optimization time (ms)')),
                ('cache_hit', models.BooleanField(db_index=True, help_text='Result from cache')),
                ('google_api_calls', models.SmallIntegerField(help_text='Number of Google API calls made (0 or 1)')),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_id', models.IntegerField(blank=True, help_text='User ID (if authenticated)', null=True)),
                ('api_version', models.CharField(default='1.0', help_text='API version', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When request was received')),
                ('completed_at', models.DateTimeField(help_text='When response was sent')),
            ],
            options={
                'verbose_name_plural': 'Route Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.DeleteModel(
            name='RouteOptimization',
        ),
        migrations.DeleteModel(
            name='TruckStop',
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['state', 'city'], name='idx_fuel_station_state_city'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['state'], name='idx_fuel_station_state'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['is_active'], name='idx_fuel_station_is_active'),
        ),
        migrations.AddIndex(
            model_name='geocodefailure',
            index=models.Index(condition=models.Q(('is_resolved', False)), fields=['original_address', 'city', 'state'], name='idx_geocode_failure_address'),
        ),
        migrations.AddIndex(
            model_name='geocodefailure',
            index=models.Index(condition=models.Q(('is_resolved', False)), fields=['next_retry_at'], name='idx_geocode_failure_retry'),
        ),
        migrations.AddIndex(
            model_name='geocodefailure',
            index=models.Index(condition=models.Q(('is_resolved', False)), fields=['google_error_code'], name='idx_geocode_failure_error'),
        ),
        migrations.AddIndex(
            model_name='priceversion',
            index=models.Index(fields=['-version_number'], name='idx_price_version_number'),
        ),
        migrations.AddIndex(
            model_name='priceversion',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active', '-published_at'], name='idx_price_version_active'),
        ),
        migrations.AddField(
            model_name='optimizationcache',
            name='version',
            field=models.ForeignKey(help_text='Price version (for invalidation)', on_delete=django.db.models.deletion.PROTECT, to='fuel_routing.priceversion'),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='version',
            field=models.ForeignKey(help_text='Price version this record belongs to', on_delete=django.db.models.deletion.PROTECT, to='fuel_routing.priceversion'),
        ),
        migrations.AddIndex(
            model_name='routecache',
            index=models.Index(fields=['cache_key'], name='idx_route_cache_key'),
        ),
        migrations.AddIndex(
            model_name='routecache',
            index=models.Index(condition=models.Q(('is_valid', True)), fields=['expires_at'], name='idx_route_cache_exp'),
        ),
        migrations.AddIndex(
            model_name='routecache',
            index=models.Index(condition=models.Q(('is_valid', True)), fields=['-last_accessed_at'], name='idx_route_cache_lru'),
        ),
        migrations.AddField(
            model_name='optimizationcache',
            name='route_cache',
            field=models.ForeignKey(help_text='Associated route', on_delete=django.db.models.deletion.CASCADE, to='fuel_routing.routecache'),
        ),
        migrations.AddIndex(
            model_name='routerequest',
            index=models.Index(fields=['request_id'], name='idx_route_request_id'),
        ),
        migrations.AddIndex(
            model_name='routerequest',
            index=models.Index(fields=['-requested_at'], name='idx_route_request_requested_at'),
        ),
        migrations.AddIndex(
            model_name='routerequest',
            index=models.Index(fields=['cache_hit', '-requested_at'], name='idx_route_request_cache_hit'),
        ),
        migrations.AddIndex(
            model_name='routerequest',
            index=models.Index(fields=['-total_fuel_cost', '-requested_at'], name='idx_route_request_cost'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(condition=models.Q(('is_current', True)), fields=['version', 'opis_id'], name='idx_price_ver_opis'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(condition=models.Q(('is_current', True)), fields=['version'], name='idx_price_ver'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(condition=models.Q(('is_current', True)), fields=['price_per_gallon'], name='idx_price_ppg'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['opis_id', '-observed_at'], name='idx_price_opis_hist'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['opis_id'], name='idx_price_opis'),
        ),
        migrations.AddIndex(
            model_name='optimizationcache',
            index=models.Index(fields=['cache_key'], name='idx_opt_cache_key'),
        ),
        migrations.AddIndex(
            model_name='optimizationcache',
            index=models.Index(condition=models.Q(('is_valid', True)), fields=['route_cache', 'version'], name='idx_opt_route_ver'),
        ),
        migrations.AddIndex(
            model_name='optimizationcache',
            index=models.Index(condition=models.Q(('is_valid', True)), fields=['expires_at'], name='idx_opt_expires'),
        ),
        migrations.AddIndex(
            model_name='optimizationcache',
            index=models.Index(condition=models.Q(('is_valid', True)), fields=['total_fuel_cost'], name='idx_opt_cost'),
        ),
    ]
