# Generated by Django 5.0.4 on 2026-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_routing', '0002_fuelprice_fuelstation_geocodefailure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude (6 decimals = 0.1m precision)', max_digits=9),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Longitude (6 decimals = 0.1m precision)', max_digits=10),
        ),
    ]


