# Generated by Django 5.0.4 on 2026-05-19 05:24

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.contrib.gis.geos import Point
from django.db import migrations, models


def populate_location_point(apps, schema_editor):
    """Backfill location_point from existing latitude/longitude fields."""
    FuelStation = apps.get_model('fuel_routing', 'FuelStation')
    batch = []
    for station in FuelStation.objects.iterator():
        try:
            lat = float(station.latitude)
            lon = float(station.longitude)
            station.location_point = Point(lon, lat, srid=4326)
            batch.append(station)
        except (ValueError, TypeError):
            continue
        if len(batch) >= 500:
            FuelStation.objects.bulk_update(batch, ['location_point'])
            batch = []
    if batch:
        FuelStation.objects.bulk_update(batch, ['location_point'])


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_routing', '0003_alter_fuelstation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='PostGIS geography point derived from lat/lon', null=True, srid=4326),
        ),
        migrations.RunPython(populate_location_point, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='fuelstation',
            index=django.contrib.postgres.indexes.GistIndex(condition=models.Q(('location_point__isnull', False)), fields=['location_point'], name='idx_fuel_station_geo_point'),
        ),
    ]
