# Generated by Django 5.0.4 on 2026-05-19 09:14

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('fuel_routing', '0004_fuelstation_location_point_gist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptimizationCache',
        ),
    ]
