# Generated by Django 5.0.4 on 2026-07-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_routing', '0005_delete_optimizationcache'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fuelstation',
            name='idx_fuel_station_geo_point',
        ),
    ]
